import { Urbanist } from "next/font/google";

import "./globals.css";
import { Header } from "@/components/header/header.app";
import { Footer } from "@/components/footer/footer.app";

const urbanist = Urbanist({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${urbanist.className} `}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
